articles/urls.py
from django.urls import path
from .views import liste_articles

urlpatterns = [
    path('', liste_articles, name='liste_articles'),
]

backoffice/urls.py
from django.urls import path
from .views import ajouter_article

urlpatterns = [
    path('ajouter-article/', ajouter_article, name='ajouter_article'),
]

connexion/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('deconnexion/', auth_views.LogoutView.as_view(next_page='home'), name='deconnexion'),
]

mercadona/urls.py
from django.contrib import admin
from django.urls import path, include
from articles.views import liste_articles
from articles import views
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from promotion import views
from django.views.generic import TemplateView

urlpatterns = [
    path('add/<int:article_id>/', views.add_promotion, name='add_promotion'),
    path('admin/', admin.site.urls),
    path('connexion/', include('connexion.urls')),
    path('backoffice/', include('backoffice.urls')),
    path('liste_articles/', liste_articles, name='liste_articles'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('promotion/', include('promotion.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

promotion/urls.py
from django.urls import path
from .views import add_promotion

app_name = 'promotion'

urlpatterns = [
   path('add_promotion/<int:article_id>/', add_promotion, name='add_promotion'),
]

articles/models.py
from django.db import models

class Article(models.Model):
    nom = models.CharField(max_length=255)
    description = models.TextField()
    categorie = models.CharField(max_length=255)
    prix = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='articles_images/')
    promotion = models.ForeignKey('promotion.Promotion', on_delete=models.SET_NULL, null=True, blank=True)

backoffice/models.py
from django.db import models
from articles.models import Article

connexion/models.py
from django.db import models

# Create your models here.

promotion/models.py
from django.db import models

# Create your models here.
class Promotion(models.Model):
    pourcentage = models.DecimalField(max_digits=5, decimal_places=2)
    date_debut = models.DateTimeField()
    date_fin = models.DateTimeField()

backoffice/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['nom', 'description', 'categorie', 'prix', 'image']

promotion/forms.py
from django import forms
from .models import Promotion

class PromotionForm(forms.ModelForm):
    class Meta:
        model = Promotion
        fields = ('pourcentage', 'date_debut', 'date_fin')

articles/views.py
from django.shortcuts import render
from .models import Article

def liste_articles(request):
    articles = Article.objects.all()
    for article in articles:
        if article.promotion:
            article.promo_price = article.prix - (article.prix * article.promotion.pourcentage / 100)
        else:
            article.promo_price = None
    return render(request, 'articles/liste_articles.html', {'articles': articles})


def home(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'home.html', context)

backoffice/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm

def ajouter_article(request):
    if not request.user.is_authenticated or not request.user.is_staff:
        return redirect('login') # Rediriger les utilisateurs non authentifiés ou non-administrateurs vers la page de connexion

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('liste_articles')
    else:
        form = ArticleForm()
    return render(request, 'backoffice/ajouter_article.html', {'form': form})

connexion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout

def login_view(request):
    form = AuthenticationForm(request, data=request.POST or None)
    if form.is_valid():
        login(request, form.get_user())
        return redirect('ajouter_article')

    return render(request, 'connexion/login.html', {'form': form})

def deconnexion(request):
    logout(request)
    return redirect('home')

promotion/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Promotion
from articles.models import Article
from .forms import PromotionForm

def add_promotion(request, article_id, promotion_id=None):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        form = PromotionForm(request.POST)
        if form.is_valid():
            promotion = form.save()
            article.promotion = promotion
            article.save()
            return redirect('liste_articles')
    else:
        form = PromotionForm()
    return render(request, 'promotion/add_promotion.html', {'form': form, 'article': article})

articles/templates/articles/liste_articles.html
{% extends 'base.html' %}

{% block content %}

<button id="promo-button">Afficher les articles en promotion</button>

<div class="row" id="article-list">
    {% for article in articles %}
    <div class="col-md-4 article-card {% if article.promotion %}promotion{% endif %}">
        <div class="card">
            <img class="card-img-top" src="{{ article.image.url }}" alt="{{ article.nom }}">
            <div class="card-body">
                <h5 class="card-title">{{ article.nom }}</h5>
                <p class="card-text">{{ article.description }}</p>
                {% if article.promotion %}
                <p class="card-text">
                    <span class="text-muted">{{ article.categorie }} - <s>{{ article.prix }} €</s></span>
                    <span class="text-danger fw-bold">{{ article.promo_price|floatformat:2 }} €</span>
                </p>
            {% else %}
                <p class="card-text"><span class="text-muted">{{ article.categorie }} - {{ article.prix }} €</span></p>
            {% endif %}
                {% if user.is_authenticated and user.is_staff %}
                <a href="{% url 'promotion:add_promotion' article.id %}" class="btn btn-primary">Ajouter une promotion</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script>
document.getElementById("promo-button").addEventListener("click", function() {
  var articleList = document.getElementById("article-list");
  var cards = articleList.getElementsByClassName("article-card");
  for (var i = 0; i < cards.length; i++) {
    if (!cards[i].classList.contains("promotion")) {
      cards[i].style.display = "none";
    }
  }
});
</script>

{% endblock %}

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mercadona{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Mercadona</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if not user.is_authenticated %}
                    <li class="nav-item {% block active_login %}{% endblock %}">
                        <a class="nav-link" href="{% url 'login' %}">Connexion</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated and user.is_staff %}
                    <li>
                        <a class="nav-link" href="{% url 'ajouter_article' %}">Ajouter un article</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="{% url 'deconnexion' %}">Déconnexion</a>
                    </li>
                {% endif %}
            
                <li class="nav-item {% block active_articles %}{% endblock %}">
                    <a class="nav-link" href="{% url 'liste_articles' %}">Catalogue</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"              integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

articles/templates/home.html
    {% extends 'base.html' %}

    {% block content %}
    <h1>Bienvenu sur votre Mercadona</h1>

    {% endblock %}

backoffice/templates/backoffice/ajouter_article.html
    {% extends 'base.html' %}

{% block content %}
    <h1>Ajouter un article</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Ajouter</button>
    </form>
{% endblock %}

connexion/templates/connexion/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Se connecter</button>
    </form>
{% endblock %}

promotion/templates/promotion/add_promotion.html
{% extends 'base.html' %}

{% block content %}
<h2>Ajouter une promotion pour "{{ article.nom }}"</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Ajouter promotion</button>
</form>
{% endblock %}